title: public notes
include:             ['_pages']
exclude:             ['_includes/notes_graph.json']

# You may need to change the base URL depending on your deploy configuration.
# Specifically, when using GitHub Pages, the baseurl should point to where GitHub
# Pages deploys your repository (which is usually the repository name).
title: Public Notes
email: lisa.k.puehl@google.com
description: >- # this means to ignore newlines until "baseurl:"
  These are some of my notes that I'm willing to put out in the open.
baseurl: "" # the subpath of your site, e.g. /blog
domain: "lisa-puehl.de"
url: "lisa-puehl.de" # the base hostname & protocol for your site, e.g. http://example.com

# Set title and content for private & broken link tooltop
privatelinks:
  title: Private or Broken Links
  msg: The page you're looking for is either not available or private!

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension:  false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

# Set to `true` to replace tweet URLs with Twitter embeds.
# Note that doing so will negatively the reader's privacy
# as their browser will communicate with Twitter's servers.
embed_tweets: false

permalink:           pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at

sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  notes:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
